Python skills to extract, transform and load real-world data about the world's largest banks into a database for further processing and querying.

In [139]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [140]:
html=requests.get("https://web.archive.org/web/20230908091635 /https://en.wikipedia.org/wiki/List_of_largest_banks").text
soup= BeautifulSoup(html,'html.parser')
# soup

In [141]:
tables = soup.find_all('tbody')
# print(tables)

In [142]:
# # from above the 2nd tbody contain data we req
rows = tables[1].find_all('tr')
# print(rows)

In [143]:
data = pd.DataFrame(columns=['Bank_Name','Total_assets_USD','Total_assets_EUR','Total_assets_GBP','Total_assets_INR'])
data

Empty DataFrame
Columns: [Bank_Name, Total_assets_USD, Total_assets_EUR, Total_assets_GBP, Total_assets_INR]
Index: []

In [144]:
dict_list=[]
for row in rows:
    col = row.find_all('td')
    if len(col)!=0 :
      k = col[1].find_all('a')
      bank = (k[1].string)
      asset=(col[2].string).strip()
      print(bank,asset)
      row_dict={
          'Bank_Name':bank,
          'Total_assets_USD': asset,
          'Total_assets_EUR':0,'Total_assets_GBP':0,'Total_assets_INR':0
      }
      dict_list.append(row_dict)

print(dict_list)

Industrial and Commercial Bank of China Limited 5,742.86
China Construction Bank 5,016.81
Agricultural Bank of China 4,919.03
Bank of China 4,192.12
JPMorgan Chase 3,868.24
Bank of America 3,051.38
Mitsubishi UFJ Financial Group 2,967.91
HSBC 2,864.59
BNP Paribas 2,849.61
Crédit Agricole 2,542.61
Citigroup Inc. 2,416.68
Postal Savings Bank of China 2,039.56
SMBC Group 2,006.75
Mizuho Financial Group 1,909.35
Bank of Communications 1,883.72
Wells Fargo 1,881.02
Banco Santander 1,853.86
Barclays 1,823.84
Japan Post Bank 1,719.92
UBS 1,679.36
Groupe BPCE 1,636.35
Société Générale 1,588.99
Royal Bank of Canada 1,544.17
Toronto-Dominion Bank 1,524.83
China Merchants Bank 1,470.00
Goldman Sachs 1,441.80
Deutsche Bank 1,428.65
Industrial Bank (China) 1,343.54
China CITIC Bank 1,239.28
Shanghai Pudong Development Bank 1,184.28
Morgan Stanley 1,180.23
Crédit Mutuel 1,180.22
Lloyds Banking Group 1,057.69
China Minsheng Bank 1,051.97
Intesa Sanpaolo 1,042.73
ING Group 1,034.32
Scotiabank 1,029.80
UniCredit 916.72
China Everbright Bank 913.49
NatWest Group 867.59
Bank of Montreal 859.05
Commonwealth Bank 837.21
Standard Chartered 819.92
La Banque postale 796.88
Ping An Bank 771.55
Banco Bilbao Vizcaya Argentaria 762.15
Norinchukin Bank 753.26
State Bank of India 694.94
Canadian Imperial Bank of Commerce 691.31
National Australia Bank 679.76
U.S.Bancorp 674.81
Rabobank 671.70
DZ Bank 670.13
Australia and New Zealand Banking Group 669.66
Westpac 653.39
Nordea 635.72
CaixaBank 604.03
Sberbank of Russia 566.07
KB Financial Group Inc 557.54
PNC Financial Services 557.26
Resona Holdings 557.10
Truist Financial Corp 555.26
DBS Bank 554.40
Danske Bank 540.66
Huaxia Bank 540.04
Shinhan Bank 537.44
China Guangfa Bank 528.91
Sumitomo Mitsui Trust Holdings 516.83
Commerzbank 510.25
Capital One 455.25
Hana Financial Group 452.34
Bank of Beijing 447.54
Itaú Unibanco 439.50
OCBC Bank 417.61
Nonghyup Bank 417.37
Bank of Jiangsu 410.83
The Bank of New York Mellon 405.78
ABN AMRO 405.67
Bank of Shanghai 405.13
Woori Bank 382.05
KBC Bank 380.33
China Zheshang Bank 380.14
Banco do Brasil 379.78
United Overseas Bank 376.07
Nomura Holdings 373.41
Landesbank Baden-Württemberg 346.45
Erste Group 346.12
Industrial Bank of Korea 343.49
Bank of Ningbo 343.05
Banco Bradesco 340.41
SEB Group 338.91
VTB Bank 335.11
Handelsbanken 331.32
DNB ASA 328.50
Qatar National Bank 323.56
National Bank of Canada 312.67
Macquarie Group 313.47
Nationwide Building Society 311.93
Raiffeisen Gruppe 303.50
First Abu Dhabi Bank 302.22
[{'Bank_Name': 'Industrial and Commercial Bank of China Limited', 'Total_assets_USD': '5,742.86', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'China Construction Bank', 'Total_assets_USD': '5,016.81', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Agricultural Bank of China', 'Total_assets_USD': '4,919.03', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Bank of China', 'Total_assets_USD': '4,192.12', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'JPMorgan Chase', 'Total_assets_USD': '3,868.24', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Bank of America', 'Total_assets_USD': '3,051.38', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Mitsubishi UFJ Financial Group', 'Total_assets_USD': '2,967.91', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'HSBC', 'Total_assets_USD': '2,864.59', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'BNP Paribas', 'Total_assets_USD': '2,849.61', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Crédit Agricole', 'Total_assets_USD': '2,542.61', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Citigroup Inc.', 'Total_assets_USD': '2,416.68', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Postal Savings Bank of China', 'Total_assets_USD': '2,039.56', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'SMBC Group', 'Total_assets_USD': '2,006.75', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Mizuho Financial Group', 'Total_assets_USD': '1,909.35', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Bank of Communications', 'Total_assets_USD': '1,883.72', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Wells Fargo', 'Total_assets_USD': '1,881.02', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Banco Santander', 'Total_assets_USD': '1,853.86', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Barclays', 'Total_assets_USD': '1,823.84', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Japan Post Bank', 'Total_assets_USD': '1,719.92', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'UBS', 'Total_assets_USD': '1,679.36', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Groupe BPCE', 'Total_assets_USD': '1,636.35', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Société Générale', 'Total_assets_USD': '1,588.99', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Royal Bank of Canada', 'Total_assets_USD': '1,544.17', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Toronto-Dominion Bank', 'Total_assets_USD': '1,524.83', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'China Merchants Bank', 'Total_assets_USD': '1,470.00', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Goldman Sachs', 'Total_assets_USD': '1,441.80', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Deutsche Bank', 'Total_assets_USD': '1,428.65', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Industrial Bank (China)', 'Total_assets_USD': '1,343.54', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'China CITIC Bank', 'Total_assets_USD': '1,239.28', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Shanghai Pudong Development Bank', 'Total_assets_USD': '1,184.28', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Morgan Stanley', 'Total_assets_USD': '1,180.23', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Crédit Mutuel', 'Total_assets_USD': '1,180.22', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Lloyds Banking Group', 'Total_assets_USD': '1,057.69', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'China Minsheng Bank', 'Total_assets_USD': '1,051.97', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Intesa Sanpaolo', 'Total_assets_USD': '1,042.73', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'ING Group', 'Total_assets_USD': '1,034.32', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Scotiabank', 'Total_assets_USD': '1,029.80', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'UniCredit', 'Total_assets_USD': '916.72', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'China Everbright Bank', 'Total_assets_USD': '913.49', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'NatWest Group', 'Total_assets_USD': '867.59', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Bank of Montreal', 'Total_assets_USD': '859.05', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Commonwealth Bank', 'Total_assets_USD': '837.21', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Standard Chartered', 'Total_assets_USD': '819.92', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'La Banque postale', 'Total_assets_USD': '796.88', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Ping An Bank', 'Total_assets_USD': '771.55', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Banco Bilbao Vizcaya Argentaria', 'Total_assets_USD': '762.15', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Norinchukin Bank', 'Total_assets_USD': '753.26', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'State Bank of India', 'Total_assets_USD': '694.94', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Canadian Imperial Bank of Commerce', 'Total_assets_USD': '691.31', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'National Australia Bank', 'Total_assets_USD': '679.76', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'U.S.Bancorp', 'Total_assets_USD': '674.81', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Rabobank', 'Total_assets_USD': '671.70', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'DZ Bank', 'Total_assets_USD': '670.13', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Australia and New Zealand Banking Group', 'Total_assets_USD': '669.66', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Westpac', 'Total_assets_USD': '653.39', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Nordea', 'Total_assets_USD': '635.72', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'CaixaBank', 'Total_assets_USD': '604.03', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Sberbank of Russia', 'Total_assets_USD': '566.07', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'KB Financial Group Inc', 'Total_assets_USD': '557.54', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'PNC Financial Services', 'Total_assets_USD': '557.26', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Resona Holdings', 'Total_assets_USD': '557.10', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Truist Financial Corp', 'Total_assets_USD': '555.26', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'DBS Bank', 'Total_assets_USD': '554.40', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Danske Bank', 'Total_assets_USD': '540.66', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Huaxia Bank', 'Total_assets_USD': '540.04', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Shinhan Bank', 'Total_assets_USD': '537.44', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'China Guangfa Bank', 'Total_assets_USD': '528.91', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Sumitomo Mitsui Trust Holdings', 'Total_assets_USD': '516.83', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Commerzbank', 'Total_assets_USD': '510.25', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Capital One', 'Total_assets_USD': '455.25', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Hana Financial Group', 'Total_assets_USD': '452.34', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Bank of Beijing', 'Total_assets_USD': '447.54', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Itaú Unibanco', 'Total_assets_USD': '439.50', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'OCBC Bank', 'Total_assets_USD': '417.61', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Nonghyup Bank', 'Total_assets_USD': '417.37', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Bank of Jiangsu', 'Total_assets_USD': '410.83', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'The Bank of New York Mellon', 'Total_assets_USD': '405.78', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'ABN AMRO', 'Total_assets_USD': '405.67', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Bank of Shanghai', 'Total_assets_USD': '405.13', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Woori Bank', 'Total_assets_USD': '382.05', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'KBC Bank', 'Total_assets_USD': '380.33', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'China Zheshang Bank', 'Total_assets_USD': '380.14', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Banco do Brasil', 'Total_assets_USD': '379.78', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'United Overseas Bank', 'Total_assets_USD': '376.07', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Nomura Holdings', 'Total_assets_USD': '373.41', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Landesbank Baden-Württemberg', 'Total_assets_USD': '346.45', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Erste Group', 'Total_assets_USD': '346.12', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Industrial Bank of Korea', 'Total_assets_USD': '343.49', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Bank of Ningbo', 'Total_assets_USD': '343.05', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Banco Bradesco', 'Total_assets_USD': '340.41', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'SEB Group', 'Total_assets_USD': '338.91', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'VTB Bank', 'Total_assets_USD': '335.11', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Handelsbanken', 'Total_assets_USD': '331.32', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'DNB ASA', 'Total_assets_USD': '328.50', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Qatar National Bank', 'Total_assets_USD': '323.56', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'National Bank of Canada', 'Total_assets_USD': '312.67', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Macquarie Group', 'Total_assets_USD': '313.47', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Nationwide Building Society', 'Total_assets_USD': '311.93', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'Raiffeisen Gruppe', 'Total_assets_USD': '303.50', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}, {'Bank_Name': 'First Abu Dhabi Bank', 'Total_assets_USD': '302.22', 'Total_assets_EUR': 0, 'Total_assets_GBP': 0, 'Total_assets_INR': 0}]

In [145]:
data=pd.DataFrame.from_dict(dict_list)
print(data)

                                          Bank_Name Total_assets_USD  \
0   Industrial and Commercial Bank of China Limited         5,742.86
1                           China Construction Bank         5,016.81
2                        Agricultural Bank of China         4,919.03
3                                     Bank of China         4,192.12
4                                    JPMorgan Chase         3,868.24
..                                              ...              ...
95                          National Bank of Canada           312.67
96                                  Macquarie Group           313.47
97                      Nationwide Building Society           311.93
98                                Raiffeisen Gruppe           303.50
99                             First Abu Dhabi Bank           302.22

    Total_assets_EUR  Total_assets_GBP  Total_assets_INR
0                  0                 0                 0
1                  0                 0                 0
2                  0                 0                 0
3                  0                 0                 0
4                  0                 0                 0
..               ...               ...               ...
95                 0                 0                 0
96                 0                 0                 0
97                 0                 0                 0
98                 0                 0                 0
99                 0                 0                 0

[100 rows x 5 columns]

In [146]:
Exchange_rate= {
    'EUR': 0.93,
    'GBP': 0.8,
    'INR': 82.95 ,
}

In [147]:
data.dtypes

Bank_Name           object
Total_assets_USD    object
Total_assets_EUR     int64
Total_assets_GBP     int64
Total_assets_INR     int64
dtype: object

In [148]:
# Data cleaning required
data['Total_assets_USD']= data['Total_assets_USD'].str.replace(',', '')

In [149]:
data['Total_assets_USD'] = data['Total_assets_USD'].astype(float)

In [150]:
data['Total_assets_EUR'] = data['Total_assets_USD'] * Exchange_rate['EUR']
data['Total_assets_GBP'] = data['Total_assets_USD'] * Exchange_rate['GBP']
data['Total_assets_INR'] = data['Total_assets_USD'] * Exchange_rate['INR']

In [151]:
data

,Bank_Name,Total_assets_USD,Total_assets_EUR,Total_assets_GBP,Total_assets_INR
0,Industrial and Commercial Bank of China Limited,5742.86,5340.8598,4594.288,476370.2370
1,China Construction Bank,5016.81,4665.6333,4013.448,416144.3895
2,Agricultural Bank of China,4919.03,4574.6979,3935.224,408033.5385
3,Bank of China,4192.12,3898.6716,3353.696,347736.3540
4,JPMorgan Chase,3868.24,3597.4632,3094.592,320870.5080
...,...,...,...,...,...
95,National Bank of Canada,312.67,290.7831,250.136,25935.9765
96,Macquarie Group,313.47,291.5271,250.776,26002.3365
97,Nationwide Building Society,311.93,290.0949,249.544,25874.5935
98,Raiffeisen Gruppe,303.50,282.2550,242.800,25175.3250
99,First Abu Dhabi Bank,302.22,281.0646,241.776,25069.1490